name: Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_URL: 'http://127.0.0.1'
      APP_PORT: '3333'
      MONGO_URL: 'mongodb://127.0.0.1:27017/aircnc'
      REDIS_HOST: '127.0.0.1'
      REDIS_PORT: '6379'
      JWT_EXPIRATION_TIME: '7d'
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCS_URL: 'https://github.com/DiegoVictor/aircnc-api#errors-reference'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          npm ci
          npm run test

      - uses: codecov/codecov-action@v3
        with:
          directory: ./tests/coverage/
